### ISSUE TITLE
Error at loading classFactory()

### ISSUE THREAD

**Issue by carlinordi** [parmendel/spatialanalysistoolbox#5]
I tried downloading from the pluging manager and from the zip, i honestly don't know about coding please help

Couldn't load plugin 'spatialanalysistoolbox' due to an error when calling its classFactory() method 
ModuleNotFoundError: No module named 'mgwr' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/carla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\spatialanalysistoolbox\__init__.py", line 36, in classFactory
    from .spatialanalysistoolbox import SpatialAnalysisToolboxPlugin
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/carla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\spatialanalysistoolbox\spatialanalysistoolbox.py", line 38, in 
    from .spatialanalysistoolbox_provider import SpatialAnalysisToolboxProvider
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/carla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\spatialanalysistoolbox\spatialanalysistoolbox_provider.py", line 35, in 
    from .algorithms.GWR_ import GWR_
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/carla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\spatialanalysistoolbox\algorithms\GWR_.py", line 26, in 
    from mgwr.gwr import GWR
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'mgwr'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.2-Firenze Firenze, b47e00ba601 

Python Path:
C:\Users/carla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lftools
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python
C:/Users/carla/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/carla/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.28.2\bin\python39.zip
C:\PROGRA~1\QGIS32~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.28.2\bin
C:\PROGRA~1\QGIS32~1.2\apps\Python39
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/carla/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by HusarArgento** [comment]
Same error. Please some help!

**Comment by PaulinaS4** [comment]
I had the same error. What I did it was install Qgis 3.40 from the osgeo and then install the packages from the osgeow4 shell.
Fiona 1.10.1
mgwr  2.1.2
esda 2.7.0
Reinstall the plugin and it worked!

If you don't have the osgweo installer, you should redirect your path to the Qgis main folder and install it with a cmd or vsc (pip install)

**Comment by Rodrigno** [comment]
Muchas gracias Paulina¡¡
Me resulto¡¡
Saludos
